-- Go-Tegs student profile-picture support
-- Run ONCE in the RESULTS / school-portal Supabase project.
-- The site uploads/removes files through its server-side service-role API;
-- students never receive the service-role key.

begin;

alter table if exists public.jss_students
  add column if not exists profile_pic_path text;

alter table if exists public.sss_students
  add column if not exists profile_pic_path text;

-- Private bucket: files are exposed to the signed URLs generated by
-- /api/student-profile.js rather than through public storage URLs.
insert into storage.buckets (id, name, public)
values ('student-profile-pics', 'student-profile-pics', false)
on conflict (id) do nothing;

update storage.buckets
set public = false
where id = 'student-profile-pics';

commit;
