-- Go-Tegs Cloudinary gallery catalogue.
-- Store only Cloudinary metadata and delivery URLs here; actual image assets
-- remain in Cloudinary and are uploaded/managed from the Cloudinary dashboard.

create table if not exists public.gallery_images (
  id bigint generated by default as identity primary key,
  title text,
  alt_text text not null default 'Go-Tegs school gallery photo',
  cloud_name text,
  public_id text,
  cloudinary_url text not null,
  display_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists gallery_images_order_idx
  on public.gallery_images (display_order, created_at desc);

alter table public.gallery_images enable row level security;

-- There is intentionally no public INSERT/UPDATE/DELETE policy.
-- Public gallery reads are served through the existing serverless admin-verify
-- function's read-only gallery feed. The service role used there bypasses RLS.

create or replace function public.set_gallery_images_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_gallery_images_updated_at on public.gallery_images;
create trigger trg_gallery_images_updated_at
before update on public.gallery_images
for each row execute function public.set_gallery_images_updated_at();
